# Generated by Django 3.2.4 on 2021-08-31 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_semname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Semname',
            new_name='Semester',
        ),
    ]
