# Generated by Django 3.2.4 on 2021-09-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_rename_semname_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=50),
        ),
    ]
