# Generated by Django 3.2.4 on 2021-09-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_alter_semester_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Sem3', 'Sem3')], max_length=50)),
                ('department', models.CharField(choices=[('Department of BBA', 'Department of BBA'), ('Department of Engineering', 'Department of Engineering')], max_length=50)),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
