# Generated by Django 3.2.4 on 2021-09-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_auto_20210901_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Answers',
        ),
    ]
