# Generated by Django 3.2.4 on 2021-09-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0009_rename_answers_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Year',
            field=models.IntegerField(choices=[('2019', '2019'), ('2018', '2018')]),
        ),
    ]
