# Generated by Django 3.2.4 on 2021-09-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0010_alter_question_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Year',
        ),
    ]
