# Generated by Django 3.2.4 on 2021-09-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0015_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
