# Generated by Django 3.2.4 on 2021-09-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0017_auto_20210904_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
