# Generated by Django 3.2.4 on 2021-09-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0018_rename_contact_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
