# Generated by Django 3.2.4 on 2021-09-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0020_auto_20210905_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(),
        ),
    ]
