# Generated by Django 3.2.4 on 2021-09-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0021_auto_20210905_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
